config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  #CRUD

  #C
  get "tasks/new", to: "tasks#new"

  post "tasks", to: "tasks#create", as: :tasks_create

  #R List all tasks
  get "tasks", to: "tasks#index"

  get "tasks/:id", to: "tasks#show", as: :task

  #U
  get "tasks/:id/edit", to: "tasks#edit", as: :edit
  patch "tasks/:id", to: "tasks#update", as: :update


  #D
  delete "tasks/:id",  to: "tasks#destroy", as: :destroy

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  def index
    @tasks = Task.all
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    @task.save

    redirect_to tasks_path(@task)
  end

  def show
    @task = Task.find(params[:id])
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.fin(params[:id])
    @task.update(all_task_params)

    redirect_to tasks_path(@tasks)
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy

    redirect_to tasks_path(@tasks)
  end

  private

  def task_params
    params.require(:task).permit(:title, :details)
  end

  def all_task_params
    params.require(:task).permit(:title, :details, :completed)
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/edit.html.erb
<div id="container">
  <h1>Update a Task </h1>
  <%= form_for(@task) do |f| %>
  <div>
    <p> <%= f.label :title %> </p>
    <%= f.text_field :title %>
  </div>

  <div>
    <p> <%= f.label :details %> </p>
    <%= f.text_field :details %>
  </div>

  <div>
    <p> <%= f.label :completed %> </p>
    <%= f.text_field :completed %>
  </div>

  <div>
   <p> <%= f.submit %> </p>
  </div>

  <% end %>
</div>

app/views/tasks/index.html.erb
<div id=container>
<h1> My Tasks </h1>

<ul>
<% @tasks.each do |task| %>
<li> <%= link_to task.title, task_path(task) %> </li>
<% end %>
</ul>
<hr>
<p id="new-task"> <%= link_to "Add a new task", tasks_new_path %> </p>
</div>

app/views/tasks/new.html.erb
<div id="container">
<h1>New Task </h1>
  <%= form_for(@task) do |f| %>
  <div>
    <p> <strong> <%= f.label :title %> </strong> </p>
    <%= f.text_field :title %>
  </div>

  <div>
    <p> <strong> <%= f.label :details %> </strong> </p>
    <%= f.text_field :details %>
  </div>

  </div>
    <%= f.submit %>
  </div>
  <% end %>

  <p id="back"> <%= link_to "Back to the list", tasks_path %> </p>
</div>

app/views/tasks/show.html.erb
<div id="container">
  <h2> <%= @task.title %> </h2>
  <p>  <%= @task.details %> </p>
  <p id="boolean"> Completed: <strong> <%= @task.completed %> </strong> </p>

  <p> <%= link_to "Back", tasks_path %> </p>
  <p> <%= link_to "Delete #{@task.title}", destroy_path(@task), method: :delete %> </p>
</div>